# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Brian Barefoot Burns
site_description: Brian's personal blog
site_url: https://bpburns.github.io/
theme:
  name: material
  features:
#    - content.action.edit
#    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link

remote_branch: main

plugins:
  - blog
  - glightbox
  - privacy
  - rss:
      match_path: blog/posts/.*
      abstract_chars_count: -1
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
        default_timezone: America/Phoenix
      categories:
        - categories
        - tags
  - search

markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables