site_name: Brian Barefoot Burns
site_description: Brian's personal blog
site_url: https://bpburns.github.io/
theme:
  name: material

remote_branch: main

plugins:
  - search
  - blog
  - rss:
      match_path: blog/posts/.*
      abstract_chars_count: -1
      date_from_meta:
        as_creation: created
        as_update: updated
        default_timezone: America/Phoenix
      categories:
        - categories
        - tags
