# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Brian Barefoot Burns
site_description: Brian's personal blog
site_url: https://bpburns.github.io/
extra:
  generator: false
theme:
  name: material
  features:
#    - content.action.edit
#    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  font:
    text: Atkinson Hyperlegible Next
    code: Atkinson Hyperlegible Mono
  palette:
    # Toggle for auto mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to Light Mode
    
    # Toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    
    # Toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to Auto Light/Dark

# Branch to use for deploying GitHub Pages
# Since this is a user site, GitHub will automatically build and deploy from
# the `main` branch instead of the `gh-pages` branch. `gh-pages` is the default
# if this is not set explicitly as it is here. The actual documentation source
# lives in the `src` branch of this repository.
remote_branch: main

plugins:
  - blog
  - glightbox
  - privacy
  - rss:
      match_path: blog/posts/.*
      abstract_chars_count: -1
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
        default_timezone: America/Phoenix
      categories:
        - categories
        - tags
      pretty_print: true
  - search

markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Recipes:
    - recipes/index.md
    - Amish Baked Oatmeal:
      - Single Batch: recipes/amish-baked-oatmeal.md
      - Double Batch: recipes/amish-baked-oatmeal-double-batch.md
  - About: about.md
